/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytx_cyberlink2android_dlna_dmc_AVMediaControllerNative */

#ifndef _Included_com_ytx_cyberlink2android_dlna_dmc_AVMediaControllerNative
#define _Included_com_ytx_cyberlink2android_dlna_dmc_AVMediaControllerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ytx_cyberlink2android_dlna_dmc_AVMediaControllerNative
 * Method:    native_mupnp_controlpoint_new
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ytx_cyberlink2android_dlna_dmc_AVMediaControllerNative_native_1mupnp_1controlpoint_1new
  (JNIEnv *, jobject);

/*
 * Class:     com_ytx_cyberlink2android_dlna_dmc_AVMediaControllerNative
 * Method:    native_setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ytx_cyberlink2android_dlna_dmc_AVMediaControllerNative_native_1setup
  (JNIEnv *, jobject);

/*
 * Class:     com_ytx_cyberlink2android_dlna_dmc_AVMediaControllerNative
 * Method:    native_mupnp_controlpoint_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ytx_cyberlink2android_dlna_dmc_AVMediaControllerNative_native_1mupnp_1controlpoint_1start
  (JNIEnv *, jobject);

/*
 * Class:     com_ytx_cyberlink2android_dlna_dmc_AVMediaControllerNative
 * Method:    native_mupnp_controlpoint_search
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ytx_cyberlink2android_dlna_dmc_AVMediaControllerNative_native_1mupnp_1controlpoint_1search
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
